# Generated by Django 5.1.3 on 2024-11-07 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(help_text='Ingresa solo texto', max_length=50, unique=True, verbose_name='Nombre :')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categoria',
                'db_table': 'Categoria',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cedula', models.CharField(max_length=10, verbose_name='Cedula: ')),
                ('Nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre :')),
                ('Apellido', models.CharField(max_length=50, unique=True, verbose_name='Apellido :')),
                ('Edad', models.IntegerField()),
                ('correo', models.EmailField(max_length=254)),
                ('domicilio', models.TextField(help_text='Escribe tu referencia: ', max_length=200)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Cliente',
                'db_table': 'Cliente',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre :')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Precio :')),
                ('stock', models.IntegerField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='datos.categoria')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Producto',
                'db_table': 'Producto',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=4)),
                ('Cliente', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='datos.cliente')),
                ('Producto', models.ManyToManyField(to='datos.producto')),
            ],
            options={
                'verbose_name': 'Orden',
                'verbose_name_plural': 'Orden',
                'db_table': 'Orden',
                'managed': True,
            },
        ),
    ]
